name: Modelo CI|CD
on:
  push:
    branches:
      - 'master'
jobs:
  model-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencias Python
        run: |
          pip install --upgrade pip
          python pip install -r requeriments.txt
      - name: Split Dataset
        run: python src/0-split-dataset.py
